baseurl = "http://example.org/"
languageCode = "en-us"
theme = "prologue"
title = "Prologue"
[params]
copyright = "Beyond the Bridge Therapy Centre "
description = "a cool company"
logo = "/uploads/Beyond the Bridge Logo.jpg"
name = "Beyond the Bridge Therapy Centre"
[[params.sidemenus]]
icon = "fa-th"
id = "portfolio-link"
link = "#portfolio"
text = "Mission Statement"
[[params.sidemenus]]
icon = "fa-user"
id = "about-link"
link = "#skill1"
text = "EMDR"
[[params.sidemenus]]
icon = "fa-user"
id = "about-link"
link = "#skill2"
text = "Art Therapy"
[[params.sidemenus]]
icon = "fa-user"
id = "about-link"
link = "#about"
text = "About Us"
[[params.sidemenus]]
icon = "fa-envelope"
id = "contact-link"
link = "#contact"
text = "Contact"
[[params.social]]
icon = "twitter"
link = "#"
medium = "twitter"
[[params.social]]
icon = "facebook"
link = "#"
medium = "facebook"
[[params.social]]
icon = "instagram"
link = "#"
medium = "instagram"
