baseurl = "http://example.org/"
languageCode = "en-us"
theme = "prologue"
title = "Prologue"
[params]
copyright = "Beyond the Bridge Therapy Centre "
description = "1 (902) 123-1234"
description2 = "1 Cool St, Cooltown, PE, Canada, C1C1C1C"
logo = "/uploads/Beyond the Bridge Logo.jpg"
name = "Beyond the Bridge Therapy Centre"
[[params.sidemenus]]
icon = "fa-rocket"
id = "portfolio-link"
link = "#portfolio"
text = "Mission Statement"
[[params.sidemenus]]
icon = "fa-eye"
id = "about-link"
link = "#skills"
text = "EMDR"
[[params.sidemenus]]
icon = "fa-paint-brush"
id = "about-link"
link = "#skills"
text = "Art Therapy"
[[params.sidemenus]]
icon = "fa-user"
id = "about-link"
link = "#about"
text = "About Us"
[[params.sidemenus]]
icon = "fa-envelope"
id = "contact-link"
link = "#contact"
text = "Contact"
[[params.social]]
icon = "twitter"
link = "#"
medium = "twitter"
[[params.social]]
icon = "facebook"
link = "#"
medium = "facebook"
[[params.social]]
icon = "instagram"
link = "#"
medium = "instagram"
