baseurl = "http://example.org/"
languageCode = "en-us"
theme = "prologue"
title = "Prologue"
[params]
copyright = "Untitled."
description = "a cool company"
name = "Beyond the Bridge Therapy Centre"
logo = "img/avatar.jpg"
[[params.sidemenus]]
id="portfolio-link"
link = "#portfolio"
text = "Mission Statement"
icon = "fa-th"
[[params.sidemenus]]
id="about-link"
link = "#skill1"
text = "EMDR"
icon = "fa-user"
[[params.sidemenus]]
id="about-link"
link = "#skill2"
text = "Art Therapy"
icon = "fa-user"
[[params.sidemenus]]
id="about-link"
link = "#about"
text = "About Us"
icon = "fa-user"
[[params.sidemenus]]
id="contact-link"
link = "#contact"
text = "Contact"
icon = "fa-envelope"
[[params.portfolio1]]
alt = ""
source = "img/pic02.jpg"
title = "Ipsum Feugiat"
url = "#"
[[params.portfolio1]]
alt = ""
source = "img/pic03.jpg"
title = "Rhoncus Semper"
url = "#"
[[params.portfolio2]]
alt = ""
source = "img/pic04.jpg"
title = "Magna Nullam"
url = "#"
[[params.portfolio2]]
alt = ""
source = "img/pic05.jpg"
title = "Natoque Vitae"
url = "#"
[[params.portfolio3]]
alt = ""
source = "img/pic06.jpg"
title = "Dolor Penatibus"
url = "#"
[[params.portfolio3]]
alt = ""
source = "img/pic07.jpg"
title = "Orci Convallis"
url = "#"
[[params.social]]
icon = "twitter"
link = "#"
medium = "twitter"
[[params.social]]
icon = "facebook"
link = "#"
medium = "facebook"
[[params.social]]
icon = "instagram"
link = "#"
medium = "instagram"