---
label: config
hide_body: false
fields:
- name: baseurl
  label: Baseurl
  type: text
  hidden: true
  default: ''
- name: languageCode
  label: Languagecode
  type: text
  hidden: true
  default: ''
- name: theme
  label: Theme
  type: text
  hidden: true
  default: ''
- name: title
  label: Title
  type: text
  hidden: true
  default: ''
- name: params
  label: Site Options
  type: field_group
  fields:
  - name: copyright
    label: Copyright
    type: text
    hidden: false
    default: ''
  - name: description
    label: Contact 1
    type: text
    hidden: false
    default: ''
    description: Probably phone number
  - name: description2
    label: Description2
    type: text
    hidden: false
    default: ''
    description: Probably address
  - name: logo
    label: Logo
    type: file
    hidden: false
    default: ''
  - name: name
    label: Name
    type: text
    hidden: false
    default: ''
  - name: sidemenus
    label: Sidemenus
    type: field_group_list
    fields:
    - name: icon
      label: Icon
      type: text
      hidden: false
      default: ''
      description: 'Use any icon here (e.g fa-compass): https://www.w3schools.com/icons/fontawesome_icons_webapp.asp'
    - name: id
      label: Id
      type: text
      hidden: true
      default: ''
    - name: link
      label: Link
      type: text
      hidden: false
      default: ''
    - name: text
      label: Text
      type: text
      hidden: false
      default: ''
    hidden: false
    default: ''
    config:
      labelField: text
  - name: social
    label: Social
    type: field_group_list
    fields:
    - name: icon
      label: Icon
      type: text
      hidden: false
      default: ''
    - name: link
      label: Link
      type: text
      hidden: false
      default: ''
    - name: medium
      label: Medium
      type: text
      hidden: false
      default: ''
    hidden: false
    default: ''
    config:
      labelField: link
  - type: field_group
    name: seo
    label: seo
    description: How googlers find your site
    fields:
    - type: text
      name: title
      label: title
      description: Main google title
    - type: textarea
      name: description
      label: description
      description: Should be max 300 characters
    - type: file
      name: image
      label: image
      description: This is the default image that will be shown when someone shares
        your site on social
  hidden: false
  default: ''
pages:
- config.toml
